"""Increase password_hash column length

Revision ID: 158efbe9e12a
Revises: 925f777d51f0
Create Date: 2025-02-01 13:12:21.534786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158efbe9e12a'
down_revision = '925f777d51f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=152),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=152),
               existing_nullable=False)

    # ### end Alembic commands ###
